# frozen_string_literal: true

perks = [
  ['Crusader of Atom', 'Inquisitor of Atom'],
  ['Destroyer of Acadia', 'Protector of Acadia'],
  'Ace Operator',
  'Action Boy/Action Girl',
  'Adamantium Skeleton',
  'Agility',
  "All Islander's Almanac Perks (Magazine)",
  'All Picket Fence Perks (Magazine)',
  'All SCAV! Perks (Magazine)',
  'Animal Friend',
  'Aquaboy / Aquagirl',
  'Armorer',
  'Astoundingly Awesome 15 (Magazine)',
  'Attack Dog',
  'Awareness',
  'Barbarian (Magazine)',
  'Barter Bobblehead',
  'Basher',
  'Berserk (Strong)',
  'Better Criticals',
  'Big Guns Bobblehead',
  'Big Leagues',
  'Blacksmith',
  'Blitz',
  'Bloody Mess',
  'Cannibal',
  'Cap Collector',
  "Captain's Feast",
  'Chem Resistant',
  'Chemist',
  'Chosen Disciple',
  'Cloak & Dagger (Deacon)',
  'Close to Metal (Nick Valenti)',
  'Combat Medic (Curie)',
  'Commando',
  'Concentrated Fire',
  'Critical Banker',
  'Demolition Expert',
  'Energy Weapons Bobblehead',
  'Explosives Bobblehead',
  'Far Harbor Survivalist',
  'Fortune Finder',
  'Four Leaf Clover',
  'Ghoulish',
  'Gift of Gab (Piper)',
  "Grim Reaper's Sprint",
  'Gun Fu',
  'Gun Nut',
  'Guns and Bullets (Magazine)',
  'Gunslinger',
  'Hacker',
  'Heavy Gunner',
  "Hunter's Wisdom (Old Longfell)",
  'Idiot Savant',
  'Inspirational',
  'Intimidation',
  'Iron Fist',
  'Isodoped (John Hancock)',
  'Killshot (Robert MacCready)',
  'Know Your Enemy (Paladin Danse)',
  'La Coiffe (Magazine)',
  'Lady Killer / Black Widow',
  'Lead Belly',
  'Lessons in Blood (Porter Gage)',
  'Lifegiver',
  'Live & Love (Magazine)',
  'Local Leader',
  'Lockpicking Bobblehead',
  'Locksmith',
  'Lone Wanderer',
  'Massachusetts Surgical Journal (Magazine)',
  'Medic',
  'Medicine Bobblehead',
  'Melee Bobblehead',
  'Mister Sandman',
  'Moving Target',
  'Mysterious Stranger',
  'Nerd Rage!',
  'Night Person',
  'Ninja',
  'Nuclear Physicist',
  'Pack Alpha',
  'Pain Train',
  'Party Boy / Party Girl',
  'Penetrator',
  'Pickpocket',
  'Quick Hands',
  'Rad Resistant',
  'Refractor',
  'Repair Bobblehead',
  'Ricochet',
  'Rifleman',
  'Robot Sympathy (Codsworth)',
  'Robotics Expert',
  'Rooted',
  'Science Bobblehead',
  'Science!',
  'Scrapper',
  'Scrounger',
  'Shield Harmonics (X6-88)',
  'Small Guns Bobblehead',
  'Sneak',
  'Sneak Bobblehead',
  'Sniper',
  'Solar Powered',
  'Speech Bobblehead',
  'Steady Aim',
  'Strong Back',
  'Tales of a Junktown Jerky Vendor (Magazine)',
  'Tesla Science (Magazine)',
  'Toughness',
  'Trigger Rush (Cait)',
  'Tumblers Today (Magazine)',
  'U.S. Covert Operations Manual (Magazine)',
  'Unarmed Bobblehead',
  'United We Stand (Preston Garvey)',
  'Unstoppables (Magazine)',
  'V.A.N.S.',
  'Wasteland Survival 9 (Magazine)',
  'Wasteland Warlord',
  'Wasteland Whisperer',
]

companions = [
  'Ada',
  'Automatron',
  'Cait',
  'Codsworth',
  'Curie',
  'Deacon',
  'Dogmeat',
  'John Hancock',
  'Nick Valentine',
  'Old Longfellow',
  'Paladin Danse',
  'Piper Wright',
  'Porter Gage',
  'Preston Garvey',
  'Robert MacCready',
  'Strong',
  'X6-88',
]

primary_weapon = [
  'Ballistic: Heavy weapons',
  'Ballistic: Pipe weapons',
  'Ballistic: Pistols',
  'Ballistic: Rifles',
  'Ballistic: Shotguns',
  'Energy: Alien',
  'Energy: Cryo',
  'Energy: Gamma',
  'Energy: Laser',
  'Energy: Plasma',
  'Explosives',
  'Melee: Bladed',
  'Melee: Blunt',
  'Melee: Fist weapons',
  'Poison weapons',
  'Traps',
]

settlements = [
  'Abernathy farm',
  'Boston Airport',
  'Bunker Hill',
  'Coastal cottage',
  'County Crossing',
  'Covenant',
  'Croup Manor',
  'Dalton farm',
  'Echo Lake Lumber',
  'Egret Tours Marina',
  'Finch Farm',
  'Graygarden',
  'Greentop Nursery',
  "Hangman's Alley",
  'Home Plate',
  'Jamaica Plain',
  'Kingsport Lighthouse',
  "Longfellow's cabin",
  'Murkwater construction site',
  "National Park visitor's center",
  'Nordhagen Beach',
  'Nuka-World Red Rocket',
  'Oberland Station',
  'Outpost Zimonja',
  'Red Rocket Truck Stop',
  'Sanctuary Hills',
  'Somerville Place',
  'Spectacle Island',
  'Starlight Drive-In',
  'Sunshine Tidings Co-op',
  'Taffington Boathouse',
  'Tenpines Bluff',
  'The Castle',
  "The Mechanist's lair",
  'The Slog',
  'Vault 88',
  'Warwick Homestead',
]

GAMES[:fallout4] = {
  title:           'Fallout 4',
  generator_title: 'Character',
  background:      'fallout4.jpg',
  added:           Date.strptime('20191216', '%Y%m%d'),
  last_updated:    Date.strptime('20191216', '%Y%m%d'),
  columns: {
    special: {
      max_per:      10,
      min:          1,
      max:          21,
      stats_column: true,
      options:      %i[Strength Perception Endurance Charisma Intelligence Agility Luck],
    },
    required_perks: {
      chance_of_multiple: 25,
      min:                3,
      max:                5,
      options:            perks,
    },
    primary_weapon: {
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            primary_weapon,
    },
    companion: {
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            companions,
    },
    primary_settlment: {
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            settlements,
    },
    freelance_theft: {
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            [
        :'No freelance theft',
        :"If its too tempting to resist",
        :Habitual,
        :"If it's not nailed down, it's yours",
      ],
    },
    unprovoked_murder: {
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            [
        :'No murder',
        :Occasional,
        :Frequent,
        :'Constant rampage',
      ],
    },
    "Faction": {
      spoiler:            true,
      chance_of_multiple: 0,
      min:                1,
      max:                1,
      options:            [
        :"The Institute",
        :"The Underground Railroad",
        :"The Brotherhood of Steel",
      ],
    },
  },
}
