default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  reaping_frequency: 10

development:
  <<: *default
  database: fletcher_development
  user: <%= ENV['FLETCHER_DATABASE_USER'] %>
  password: <%= ENV['FLETCHER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>

test:
  <<: *default
  database: fletcher_test

production:
  <<: *default
  database: <%= ENV['FLETCHER_DATABASE_NAME'] %>
  user: <%= ENV['FLETCHER_DATABASE_USER'] %>
  password: <%= ENV['FLETCHER_DATABASE_PASSWORD'] %>
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
