json.id product.id
json.company product.company
json.slug product.slug
json.name product.name
json.short_desc product.short_desc
json.description product.description
json.image product.image
json.rating product.rating
json.total_reviews product.total_reviews
json.quality_score product.quality_score_cache
json.price_score product.price_score_cache
